static char CopyrightEyeCatcher[] =
  "***** NOTICE:"
  "APPLICATION COPYRIGHT 1995-1998 UNITED COMPUTER SALES & SERVICES, INC. "
  "SOURCE CODE COPYRIGHT 1995-1998 LARRY REEVE AS AN UNPUBLISHED WORK. "
  "ALL RIGHTS RESERVED. "
  "DUPLICATION AND DISTRIBUTION RESTRICTED TO LICENSED USERS ONLY."
  "******";
